### ISSUE TITLE
缺少步骤

### ISSUE THREAD

**Issue by 011011100** [elonehoo/vitepress-theme-simple#3]
缺少对标题github的更改。
我认为这样一个个改真的好麻烦，为什么不能像java一样把GitHub账户地址写再yml文件或者别的文件里面，直接改一个改全部。
非常方便。

**Comment by elonehoo** [comment]
嗯，我觉得 `yml` 不如 `json` ，可以使用一个通用的 `json` 文件进行管理。

**Comment by elonehoo** [comment]
增加了一个 `config.json` 进行配置。

故而关闭改issue
